//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17020
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LocalizedResourceExtension.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("LocalizedResourceExtension.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy resources from the neutral culture.
        /// </summary>
        public static string CopyResources {
            get {
                return ResourceManager.GetString("CopyResources", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Culture code.
        /// </summary>
        public static string CultureCode {
            get {
                return ResourceManager.GetString("CultureCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Custom culture.
        /// </summary>
        public static string CustomCulture {
            get {
                return ResourceManager.GetString("CustomCulture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Known culture.
        /// </summary>
        public static string KnownCulture {
            get {
                return ResourceManager.GetString("KnownCulture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add as a subitem of the neutral culture resource file.
        /// </summary>
        public static string MakeSubItem {
            get {
                return ResourceManager.GetString("MakeSubItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (Neutral).
        /// </summary>
        public static string Neutral {
            get {
                return ResourceManager.GetString("Neutral", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        public static string OK {
            get {
                return ResourceManager.GetString("OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Target culture.
        /// </summary>
        public static string TargetCulture {
            get {
                return ResourceManager.GetString("TargetCulture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add localization for {0}.
        /// </summary>
        public static string WindowTitleFormat {
            get {
                return ResourceManager.GetString("WindowTitleFormat", resourceCulture);
            }
        }
    }
}
