//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mediatek.Web.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Mediatek.Web.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The current password is incorrect or the new password is invalid..
        /// </summary>
        internal static string The_current_password_is_incorrect_or_the_new_password_is_invalid_ {
            get {
                return ResourceManager.GetString("The_current_password_is_incorrect_or_the_new_password_is_invalid_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The new password and confirmation password do not match..
        /// </summary>
        internal static string The_new_password_and_confirmation_password_do_not_match_ {
            get {
                return ResourceManager.GetString("The_new_password_and_confirmation_password_do_not_match_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The username or password provided is incorrect..
        /// </summary>
        internal static string The_username_or_password_provided_is_incorrect_ {
            get {
                return ResourceManager.GetString("The_username_or_password_provided_is_incorrect_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome to Mediatek Web!.
        /// </summary>
        internal static string Welcome_to_Mediatek_Web_ {
            get {
                return ResourceManager.GetString("Welcome_to_Mediatek_Web_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must specify a current password..
        /// </summary>
        internal static string You_must_specify_a_current_password_ {
            get {
                return ResourceManager.GetString("You_must_specify_a_current_password_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must specify a password..
        /// </summary>
        internal static string You_must_specify_a_password_ {
            get {
                return ResourceManager.GetString("You_must_specify_a_password_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must specify a password of {0} or more characters..
        /// </summary>
        internal static string You_must_specify_a_password_of__0__or_more_characters_ {
            get {
                return ResourceManager.GetString("You_must_specify_a_password_of__0__or_more_characters_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must specify a username..
        /// </summary>
        internal static string You_must_specify_a_username_ {
            get {
                return ResourceManager.GetString("You_must_specify_a_username_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must specify an email address..
        /// </summary>
        internal static string You_must_specify_an_email_address_ {
            get {
                return ResourceManager.GetString("You_must_specify_an_email_address_", resourceCulture);
            }
        }
    }
}
