//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.454
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SharpDB.Properties {
    using System;
    
    
    /// <summary>
    ///   Une classe de ressource fortement typée destinée, entre autres, à la consultation des chaînes localisées.
    /// </summary>
    // Cette classe a été générée automatiquement par la classe StronglyTypedResourceBuilder
    // à l'aide d'un outil, tel que ResGen ou Visual Studio.
    // Pour ajouter ou supprimer un membre, modifiez votre fichier .ResX, puis réexécutez ResGen
    // avec l'option /str ou régénérez votre projet VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Retourne l'instance ResourceManager mise en cache utilisée par cette classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SharpDB.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Remplace la propriété CurrentUICulture du thread actuel pour toutes
        ///   les recherches de ressources à l'aide de cette classe de ressource fortement typée.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à {0} rows affected.
        /// </summary>
        public static string affected_rows_format {
            get {
                return ResourceManager.GetString("affected_rows_format", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à SharpDB.
        /// </summary>
        public static string ApplicationName {
            get {
                return ResourceManager.GetString("ApplicationName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Type: {0}.
        /// </summary>
        public static string column_datatype_format {
            get {
                return ResourceManager.GetString("column_datatype_format", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Default value: {0}.
        /// </summary>
        public static string column_default_value_format {
            get {
                return ResourceManager.GetString("column_default_value_format", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Do you really want to delete this database connection ?.
        /// </summary>
        public static string confirm_delete_connection {
            get {
                return ResourceManager.GetString("confirm_delete_connection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Really delete ?.
        /// </summary>
        public static string confirm_delete_connection_title {
            get {
                return ResourceManager.GetString("confirm_delete_connection_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Confirmation.
        /// </summary>
        public static string confirmation {
            get {
                return ResourceManager.GetString("confirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Connect to database.
        /// </summary>
        public static string connect_database {
            get {
                return ResourceManager.GetString("connect_database", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à New database connection.
        /// </summary>
        public static string connection_default_name {
            get {
                return ResourceManager.GetString("connection_default_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Connection name.
        /// </summary>
        public static string connection_name {
            get {
                return ResourceManager.GetString("connection_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Connection string.
        /// </summary>
        public static string connection_string {
            get {
                return ResourceManager.GetString("connection_string", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Copy.
        /// </summary>
        public static string copy {
            get {
                return ResourceManager.GetString("copy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Current database.
        /// </summary>
        public static string current_database {
            get {
                return ResourceManager.GetString("current_database", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Cut.
        /// </summary>
        public static string cut {
            get {
                return ResourceManager.GetString("cut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Data provider.
        /// </summary>
        public static string data_provider {
            get {
                return ResourceManager.GetString("data_provider", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Not connected to the database.
        /// </summary>
        public static string database_not_connected {
            get {
                return ResourceManager.GetString("database_not_connected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Delete database connection.
        /// </summary>
        public static string delete_database_connection {
            get {
                return ResourceManager.GetString("delete_database_connection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Cancel.
        /// </summary>
        public static string dialog_cancel {
            get {
                return ResourceManager.GetString("dialog_cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à OK.
        /// </summary>
        public static string dialog_ok {
            get {
                return ResourceManager.GetString("dialog_ok", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Disconnect from database.
        /// </summary>
        public static string disconnect_database {
            get {
                return ResourceManager.GetString("disconnect_database", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Edit database connection.
        /// </summary>
        public static string edit_database_connection {
            get {
                return ResourceManager.GetString("edit_database_connection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Error.
        /// </summary>
        public static string error {
            get {
                return ResourceManager.GetString("error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Execute all statements as a script.
        /// </summary>
        public static string execute_as_script {
            get {
                return ResourceManager.GetString("execute_as_script", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Execute current statement.
        /// </summary>
        public static string execute_current {
            get {
                return ResourceManager.GetString("execute_current", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Explain plan.
        /// </summary>
        public static string explain_plan {
            get {
                return ResourceManager.GetString("explain_plan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Total {0} rows.
        /// </summary>
        public static string fetched_rows_complete_format {
            get {
                return ResourceManager.GetString("fetched_rows_complete_format", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Fetched {0} rows (scroll down for more).
        /// </summary>
        public static string fetched_rows_incomplete_format {
            get {
                return ResourceManager.GetString("fetched_rows_incomplete_format", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Column.
        /// </summary>
        public static string ItemType_Column {
            get {
                return ResourceManager.GetString("ItemType_Column", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Index.
        /// </summary>
        public static string ItemType_Index {
            get {
                return ResourceManager.GetString("ItemType_Index", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Table.
        /// </summary>
        public static string ItemType_Table {
            get {
                return ResourceManager.GetString("ItemType_Table", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Recent databases.
        /// </summary>
        public static string jumplist_recent_databases {
            get {
                return ResourceManager.GetString("jumplist_recent_databases", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Recent files.
        /// </summary>
        public static string jumplist_recent_files {
            get {
                return ResourceManager.GetString("jumplist_recent_files", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à New database connection.
        /// </summary>
        public static string new_database_connection {
            get {
                return ResourceManager.GetString("new_database_connection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à New worksheet.
        /// </summary>
        public static string new_worksheet {
            get {
                return ResourceManager.GetString("new_worksheet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Untitled{0}.
        /// </summary>
        public static string new_worksheet_name_format {
            get {
                return ResourceManager.GetString("new_worksheet_name_format", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à No database is selected.
        /// </summary>
        public static string no_database_selected {
            get {
                return ResourceManager.GetString("no_database_selected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à No handler exists for this type of file.
        /// </summary>
        public static string no_handler_for_file {
            get {
                return ResourceManager.GetString("no_handler_for_file", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Open worksheet.
        /// </summary>
        public static string open_worksheet {
            get {
                return ResourceManager.GetString("open_worksheet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Paste.
        /// </summary>
        public static string paste {
            get {
                return ResourceManager.GetString("paste", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à An error occured while executing the query:.
        /// </summary>
        public static string query_error {
            get {
                return ResourceManager.GetString("query_error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Output.
        /// </summary>
        public static string query_output {
            get {
                return ResourceManager.GetString("query_output", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Results.
        /// </summary>
        public static string query_results {
            get {
                return ResourceManager.GetString("query_results", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Query successfully executed.
        /// </summary>
        public static string query_success {
            get {
                return ResourceManager.GetString("query_success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Refresh database structure.
        /// </summary>
        public static string refresh_model {
            get {
                return ResourceManager.GetString("refresh_model", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à This document has unsaved changes. Do you want to save them now ?.
        /// </summary>
        public static string save_changes_before_close {
            get {
                return ResourceManager.GetString("save_changes_before_close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Save worksheet.
        /// </summary>
        public static string save_worksheet {
            get {
                return ResourceManager.GetString("save_worksheet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à SQL files.
        /// </summary>
        public static string sql_file_filter_name {
            get {
                return ResourceManager.GetString("sql_file_filter_name", resourceCulture);
            }
        }
    }
}
