//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SharpDB.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SharpDB.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} rows affected.
        /// </summary>
        public static string affected_rows_format {
            get {
                return ResourceManager.GetString("affected_rows_format", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SharpDB.
        /// </summary>
        public static string ApplicationName {
            get {
                return ResourceManager.GetString("ApplicationName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you really want to delete this database connection ?.
        /// </summary>
        public static string confirm_delete_connection {
            get {
                return ResourceManager.GetString("confirm_delete_connection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Really delete ?.
        /// </summary>
        public static string confirm_delete_connection_title {
            get {
                return ResourceManager.GetString("confirm_delete_connection_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirmation.
        /// </summary>
        public static string confirmation {
            get {
                return ResourceManager.GetString("confirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connect to database.
        /// </summary>
        public static string connect_database {
            get {
                return ResourceManager.GetString("connect_database", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New database connection.
        /// </summary>
        public static string connection_default_name {
            get {
                return ResourceManager.GetString("connection_default_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connection name.
        /// </summary>
        public static string connection_name {
            get {
                return ResourceManager.GetString("connection_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connection string.
        /// </summary>
        public static string connection_string {
            get {
                return ResourceManager.GetString("connection_string", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy.
        /// </summary>
        public static string copy {
            get {
                return ResourceManager.GetString("copy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current database.
        /// </summary>
        public static string current_database {
            get {
                return ResourceManager.GetString("current_database", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cut.
        /// </summary>
        public static string cut {
            get {
                return ResourceManager.GetString("cut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data provider.
        /// </summary>
        public static string data_provider {
            get {
                return ResourceManager.GetString("data_provider", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not connected to the database.
        /// </summary>
        public static string database_not_connected {
            get {
                return ResourceManager.GetString("database_not_connected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete database connection.
        /// </summary>
        public static string delete_database_connection {
            get {
                return ResourceManager.GetString("delete_database_connection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string dialog_cancel {
            get {
                return ResourceManager.GetString("dialog_cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        public static string dialog_ok {
            get {
                return ResourceManager.GetString("dialog_ok", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disconnect from database.
        /// </summary>
        public static string disconnect_database {
            get {
                return ResourceManager.GetString("disconnect_database", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit database connection.
        /// </summary>
        public static string edit_database_connection {
            get {
                return ResourceManager.GetString("edit_database_connection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        public static string error {
            get {
                return ResourceManager.GetString("error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Execute all statements as a script.
        /// </summary>
        public static string execute_as_script {
            get {
                return ResourceManager.GetString("execute_as_script", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Execute current statement.
        /// </summary>
        public static string execute_current {
            get {
                return ResourceManager.GetString("execute_current", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Explain plan.
        /// </summary>
        public static string explain_plan {
            get {
                return ResourceManager.GetString("explain_plan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total {0} rows.
        /// </summary>
        public static string fetched_rows_complete_format {
            get {
                return ResourceManager.GetString("fetched_rows_complete_format", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fetched {0} rows (scroll down for more).
        /// </summary>
        public static string fetched_rows_incomplete_format {
            get {
                return ResourceManager.GetString("fetched_rows_incomplete_format", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New database connection.
        /// </summary>
        public static string new_database_connection {
            get {
                return ResourceManager.GetString("new_database_connection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New worksheet.
        /// </summary>
        public static string new_worksheet {
            get {
                return ResourceManager.GetString("new_worksheet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Untitled{0}.
        /// </summary>
        public static string new_worksheet_name_format {
            get {
                return ResourceManager.GetString("new_worksheet_name_format", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No database is selected.
        /// </summary>
        public static string no_database_selected {
            get {
                return ResourceManager.GetString("no_database_selected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open worksheet.
        /// </summary>
        public static string open_worksheet {
            get {
                return ResourceManager.GetString("open_worksheet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paste.
        /// </summary>
        public static string paste {
            get {
                return ResourceManager.GetString("paste", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occured while executing the query:.
        /// </summary>
        public static string query_error {
            get {
                return ResourceManager.GetString("query_error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Output.
        /// </summary>
        public static string query_output {
            get {
                return ResourceManager.GetString("query_output", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Results.
        /// </summary>
        public static string query_results {
            get {
                return ResourceManager.GetString("query_results", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Query successfully executed.
        /// </summary>
        public static string query_success {
            get {
                return ResourceManager.GetString("query_success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This document has unsaved changes. Do you want to save before closing ?.
        /// </summary>
        public static string save_changes_before_close {
            get {
                return ResourceManager.GetString("save_changes_before_close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save worksheet.
        /// </summary>
        public static string save_worksheet {
            get {
                return ResourceManager.GetString("save_worksheet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SQL files.
        /// </summary>
        public static string sql_file_filter_name {
            get {
                return ResourceManager.GetString("sql_file_filter_name", resourceCulture);
            }
        }
    }
}
