//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SharpDB.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SharpDB.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SharpDB.
        /// </summary>
        internal static string ApplicationName {
            get {
                return ResourceManager.GetString("ApplicationName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you really want to delete this database connection ?.
        /// </summary>
        internal static string confirm_delete_connection {
            get {
                return ResourceManager.GetString("confirm_delete_connection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Really delete ?.
        /// </summary>
        internal static string confirm_delete_connection_title {
            get {
                return ResourceManager.GetString("confirm_delete_connection_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connect to database.
        /// </summary>
        internal static string connect_database {
            get {
                return ResourceManager.GetString("connect_database", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New database connection.
        /// </summary>
        internal static string connection_default_name {
            get {
                return ResourceManager.GetString("connection_default_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete database connection.
        /// </summary>
        internal static string delete_database_connection {
            get {
                return ResourceManager.GetString("delete_database_connection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string dialog_cancel {
            get {
                return ResourceManager.GetString("dialog_cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        internal static string dialog_ok {
            get {
                return ResourceManager.GetString("dialog_ok", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disconnect from database.
        /// </summary>
        internal static string disconnect_database {
            get {
                return ResourceManager.GetString("disconnect_database", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit database connection.
        /// </summary>
        internal static string edit_database_connection {
            get {
                return ResourceManager.GetString("edit_database_connection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New database connection.
        /// </summary>
        internal static string new_database_connection {
            get {
                return ResourceManager.GetString("new_database_connection", resourceCulture);
            }
        }
    }
}
