//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3053
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MediaTek.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MediaTek.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to res://*/DataModel.DvdModel.csdl|res://*/DataModel.DvdModel.ssdl|res://*/DataModel.DvdModel.msl.
        /// </summary>
        internal static string dbMetaData {
            get {
                return ResourceManager.GetString("dbMetaData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All images|*.bmp;*.jpg;*.jpeg;*.png;*.gif;*.tiff;*.tif;*.wdp|Bitmap images|*.bmp|JPEG images|*.jpg;*.jpeg|GIF images|*.gif|PNG images|*.png|TIFF images|*.tif;*.tiff|Windows Media Photo images|*.wdp|All files|*.*.
        /// </summary>
        internal static string imageFilters {
            get {
                return ResourceManager.GetString("imageFilters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CREATE TABLE language (
        ///	id integer not null primary key autoincrement,
        ///	name text(100) not null,
        ///	code text(10),
        ///	picture blob
        ///);
        ///
        ///CREATE TABLE &apos;country&apos; (
        ///	id integer not null primary key autoincrement,
        ///	name text(200) not null,
        ///	language_id integer,
        ///	flag blob,
        ///	foreign key (language_id) references language(id)
        ///);
        ///
        ///CREATE TABLE director(
        ///	id integer not null primary key autoincrement,
        ///	name text(200) not null,
        ///	country_id integer,
        ///	picture blob,
        ///	foreign key (country_id) references co [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string schema_sql {
            get {
                return ResourceManager.GetString("schema_sql", resourceCulture);
            }
        }
        
        internal static byte[] template_db {
            get {
                object obj = ResourceManager.GetObject("template_db", resourceCulture);
                return ((byte[])(obj));
            }
        }
    }
}
