//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.431
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PasteBinSharp.UI.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PasteBinSharp.UI.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login error:.
        /// </summary>
        public static string Error_Login {
            get {
                return ResourceManager.GetString("Error_Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Missing information.
        /// </summary>
        public static string Error_MissingInformation {
            get {
                return ResourceManager.GetString("Error_MissingInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error sending to PasteBin:.
        /// </summary>
        public static string Error_Sending {
            get {
                return ResourceManager.GetString("Error_Sending", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        public static string Error_Title {
            get {
                return ResourceManager.GetString("Error_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string General_Cancel {
            get {
                return ResourceManager.GetString("General_Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        public static string General_OK {
            get {
                return ResourceManager.GetString("General_OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string General_Settings {
            get {
                return ResourceManager.GetString("General_Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expiration.
        /// </summary>
        public static string Paste_Expiration {
            get {
                return ResourceManager.GetString("Paste_Expiration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Format.
        /// </summary>
        public static string Paste_Format {
            get {
                return ResourceManager.GetString("Paste_Format", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Post anonymously.
        /// </summary>
        public static string Paste_PostAnonymously {
            get {
                return ResourceManager.GetString("Paste_PostAnonymously", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Post as.
        /// </summary>
        public static string Paste_PostAsUser {
            get {
                return ResourceManager.GetString("Paste_PostAsUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Private.
        /// </summary>
        public static string Paste_Private {
            get {
                return ResourceManager.GetString("Paste_Private", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Text.
        /// </summary>
        public static string Paste_Text {
            get {
                return ResourceManager.GetString("Paste_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title.
        /// </summary>
        public static string Paste_Title {
            get {
                return ResourceManager.GetString("Paste_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (not set).
        /// </summary>
        public static string Paste_UserNotSet {
            get {
                return ResourceManager.GetString("Paste_UserNotSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send to PasteBin.
        /// </summary>
        public static string SendWindow_Title {
            get {
                return ResourceManager.GetString("SendWindow_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to API Key.
        /// </summary>
        public static string Settings_APIKey {
            get {
                return ResourceManager.GetString("Settings_APIKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        public static string Settings_Password {
            get {
                return ResourceManager.GetString("Settings_Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error decoding password. Please enter your password again..
        /// </summary>
        public static string Settings_PasswordDecodeFailed {
            get {
                return ResourceManager.GetString("Settings_PasswordDecodeFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User name.
        /// </summary>
        public static string Settings_UserName {
            get {
                return ResourceManager.GetString("Settings_UserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string SettingsWindow_Title {
            get {
                return ResourceManager.GetString("SettingsWindow_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The API Key must be set.
        /// </summary>
        public static string Validation_APIKeyMustBeSet {
            get {
                return ResourceManager.GetString("Validation_APIKeyMustBeSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Would you like to edit the settings?.
        /// </summary>
        public static string Validation_EditSettingsQuestion {
            get {
                return ResourceManager.GetString("Validation_EditSettingsQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The password must be set if the user name is set.
        /// </summary>
        public static string Validation_PasswordMustBeSet {
            get {
                return ResourceManager.GetString("Validation_PasswordMustBeSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Text field can&apos;t be empty.
        /// </summary>
        public static string Validation_TextCantBeEmpty {
            get {
                return ResourceManager.GetString("Validation_TextCantBeEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The user name and password must be set.
        /// </summary>
        public static string Validation_UserNameAndPasswordMustBeSet {
            get {
                return ResourceManager.GetString("Validation_UserNameAndPasswordMustBeSet", resourceCulture);
            }
        }
    }
}
